import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased
          bg-gradient-to-tr from-gray-100 via-gray-200 to-gray-300
         dark:from-gray-900 dark:via-gray-800 dark:to-gray-950
          transition-colors duration-500`
        }
      >
        {children}
      </body>
    </html>
  );
}
