import type { Metadata } from "next";
import "./globals.css";
import theme from "@/lib/theme";
import "@fontsource/major-mono-display";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased
          ${theme}`
        }
      >
        
        {children}
      </body>
    </html>
  );
}
